# Generated by Django 4.2.7 on 2023-11-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superhero',
            name='image',
            field=models.ImageField(db_column='image_id', default='Image not available', upload_to='images/'),
        ),
    ]
