# Generated by Django 4.2.7 on 2023-11-02 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superhero',
            name='description',
        ),
        migrations.RemoveField(
            model_name='superhero',
            name='image',
        ),
        migrations.RemoveField(
            model_name='superhero',
            name='strength',
        ),
        migrations.RemoveField(
            model_name='superhero',
            name='weakness',
        ),
    ]
