# Generated by Django 4.2.7 on 2023-11-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0003_superhero_description_superhero_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superhero',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='identity',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='image',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='strengths',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='weaknesses',
            field=models.CharField(max_length=200),
        ),
    ]
