# Generated by Django 4.2.7 on 2023-11-07 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0004_alter_superhero_description_alter_superhero_identity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superhero',
            name='description',
            field=models.TextField(default='NONE'),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='identity',
            field=models.CharField(default='NONE', max_length=200),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='image',
            field=models.CharField(default='NONE', max_length=200),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='name',
            field=models.CharField(default='NONE', max_length=200),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='strengths',
            field=models.CharField(default='NONE', max_length=200),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='weaknesses',
            field=models.CharField(default='NONE', max_length=200),
        ),
    ]
