# Generated by Django 4.2.7 on 2023-11-07 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0002_remove_superhero_description_remove_superhero_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='superhero',
            name='description',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='superhero',
            name='image',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='superhero',
            name='strengths',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='superhero',
            name='weaknesses',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
