# Generated by Django 4.2.7 on 2023-11-10 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Article...', max_length=50)),
                ('hero', models.CharField(max_length=50)),
                ('articles', models.TextField(default='Write your article here...')),
            ],
        ),
        migrations.RemoveField(
            model_name='superhero',
            name='articles',
        ),
        migrations.AlterField(
            model_name='superhero',
            name='identity',
            field=models.CharField(default='Identity', max_length=200),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='name',
            field=models.CharField(default='Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='strengths',
            field=models.CharField(default='Strengths...', max_length=200),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='weaknesses',
            field=models.CharField(default='Weaknesses...', max_length=200),
        ),
    ]
