# Generated by Django 4.2.7 on 2023-11-10 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0003_article_remove_superhero_articles_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.AddField(
            model_name='superhero',
            name='article',
            field=models.TextField(default='Write your article here...'),
        ),
        migrations.AddField(
            model_name='superhero',
            name='author',
            field=models.CharField(default='Author...', max_length=50),
        ),
        migrations.AddField(
            model_name='superhero',
            name='title',
            field=models.CharField(default='Article...', max_length=50),
        ),
    ]
