# Generated by Django 4.2.7 on 2023-11-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Superhero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name', max_length=200)),
                ('identity', models.CharField(default='Identity', max_length=200)),
                ('description', models.TextField(default='Description of Superhero')),
                ('strengths', models.CharField(default='Strengths...', max_length=200)),
                ('weaknesses', models.CharField(default='Weaknesses...', max_length=200)),
                ('image', models.CharField(default='NONE', max_length=200)),
                ('title', models.CharField(default='Article...', max_length=50)),
                ('author', models.CharField(default='Author...', max_length=50)),
                ('article', models.TextField(default='Write your article here...')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
