envs:
- key: DEBUG
  scope: RUN_AND_BUILD_TIME
  value: "True"
- key: DISABLE_COLLECTSTATIC
  scope: RUN_AND_BUILD_TIME
  value: "1"
name: webapps-demo
region: nyc
services:
- environment_slug: python
  github:
    branch: main
    deploy_on_push: true
    repo: RyanRonish/PythonWebApps
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: webapps-demo-django
  routes:
  - path: /
  run_command: |
    python manage.py migrate --no-input
    gunicorn --worker-tmp-dir /dev/shm config.wsgi
  source_dir: week8/Superhero
static_sites:
- environment_slug: html
  github:
    branch: main
    deploy_on_push: true
    repo: RyanRonish/PythonWebApps
  name: webapps-demo-static
  routes:
  - path: /static
  source_dir: week8/Superhero/static
  alerts:
   - rule: DEPLOYMENT_FAILED
   - rule: DOMAIN_FAILED
  services:
   - environment_slug: python
      envs:
      - key: DISABLE_COLLECTSTATIC
        scope: RUN_AND_BUILD_TIME
        value: "1"
    databases:
    - engine: PG
      name: db
      num_nodes: 1
      size: db-s-dev-database
      version: "12"
    services:
    - environment_slug: python
      envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
      - key: POSTGRES_DB
        scope: RUN_AND_BUILD_TIME
        value: ${db.DATABASE}
      - key: POSTGRES_HOST
        scope: RUN_AND_BUILD_TIME
        value: ${db.HOSTNAME}
      - key: POSTGRES_USER
        scope: RUN_AND_BUILD_TIME
        value: ${db.USERNAME}
      - key: POSTGRES_PASSWORD
        scope: RUN_AND_BUILD_TIME
        value: ${db.PASSWORD}
      - key: POSTGRES_PORT
        scope: RUN_AND_BUILD_TIME
        value: ${db.PORT}