databases:
- engine: PG
  name: db
  version: "12"
envs:
- key: DEBUG
  scope: RUN_AND_BUILD_TIME
  value: "True"
- key: DISABLE_COLLECTSTATIC
  scope: RUN_AND_BUILD_TIME
  value: "1"
ingress:
  rules:
  - component:
      name: webapps-demo-django
    match:
      path:
        prefix: /
  - component:
      name: webapps-demo-static
    match:
      path:
        prefix: /static
name: webapps-demo
region: nyc
services:
- environment_slug: python
  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${db.DATABASE_URL}
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${db.DATABASE_URL}
  github:
    branch: main
    deploy_on_push: true
    repo: RyanRonish/PythonWebApps
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: webapps-demo-django
  run_command: |
    python manage.py migrate --no-input
    python manag.py loaddata database.json
    gunicorn --worker-tmp-dir /dev/shm config.wsgi
  source_dir: week8/Superhero
static_sites:
- environment_slug: html
  github:
    branch: main
    deploy_on_push: true
    repo: RyanRonish/PythonWebApps
  name: webapps-demo-static
  source_dir: week8/Superhero/static